Fix Script: add first packages in Linux before

diff --git a/.chezmoiscripts/run_onchange_before_linux-install-packages.sh.tmpl b/.chezmoiscripts/run_onchange_before_linux-install-packages.sh.tmpl
--- a/.chezmoiscripts/run_onchange_before_linux-install-packages.sh.tmpl
+++ b/.chezmoiscripts/run_onchange_before_linux-install-packages.sh.tmpl
@@ -5,6 +5,7 @@
 {{- /* https://github.com/mriehl/dotfiles/blob/master/run_onchange_packages.sh.tmpl */ -}}
 #!/usr/bin/env bash
 
+pacmanFirst_packages=( {{.packages.linux.manjaro.pacman_first | quoteList | join " " }})
 pacman_packages=( {{.packages.linux.manjaro.pacman | quoteList | join " " }})
 aur_packages=( {{.packages.linux.manjaro.aur | quoteList | join " " }})
 
@@ -13,6 +14,18 @@ installed_packages=($(pacman -Qq))
 is_installed() {
   [[ " ${installed_packages[*]} " =~ " $1 " ]]
 }
+
+to_install_pacmanFirst=()
+for package in "${pacmanFirst_packages[@]}"; do
+  if ! is_installed "$package"; then
+    to_install_pacmanFirst+=("$package")
+  fi
+done
+
+if [[ ${#to_install_pacmanFirst[@]} -gt 0 ]]; then
+  echo "  - Installing missing packages via pacman: ${to_install_pacmanFirst[@]}"
+  sudo pacman -S --needed --noconfirm "${to_install_pacmanFirst[@]}"
+fi
 
 to_install_pacman=()
 for package in "${pacman_packages[@]}"; do
@@ -23,12 +36,12 @@ done
 
 if [[ ${#to_install_pacman[@]} -gt 0 ]]; then
   echo "  - Installing missing packages via pacman: ${to_install_pacman[@]}"
-  sudo pacman -S --noconfirm "${to_install_pacman[@]}"
+  sudo pacman -S --needed --noconfirm "${to_install_pacman[@]}"
 fi
 
 if ! is_installed "yay"; then
   echo "  - Installing yay"
-  sudo pacman -S --noconfirm yay
+  sudo pacman -S --needed --noconfirm yay
 fi
 
 to_install_aur=()
